config/routes.rb
Pictures::Application.routes.draw do

  root :to => "Picapp#welcome", as: 'welcome'
  get "/user/index"

  resources :photos
  resources :users

  get '/photos/:id/destroy' => 'Photos#destroy'
  get '/error' => 'Picapp#error'
  get '/error2' => 'Picapp#error2'
  post '/comments/new/:id' => 'Comments#new'
  get '/follows/present/:id' => 'Follows#present'
  get '/follows/show/:id' => 'Follows#show'
  get '/follows/new/:id' => 'Follows#create'
  get '/follows/destroy/:id' => 'Follows#destroy'
  post '/search' => 'Picapp#search', as: 'search'
  get '/welcome' =>'Picapp#welcome', as: 'welcome'
  get '/home' =>'Picapp#home', as: 'home'
  get '/sessions/destroy' =>'Sessions#destroy'
  get '/sessions/new' => 'Sessions#new', as: 'new_session'
  post '/sessions' => 'Sessions#create', as: 'sessions'
  delete '/sessions' => 'Sessions#destroy', as: 'session'

  match ':controller(/:action(/:id))', :via => :get

  match ':controller(/:action(/:id(.:format)))', :via => :get

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :detail, :image, :user_id
  validates :image, presence: true
  belongs_to :user
  has_many :comment
  mount_uploader :image, ImageUploader



  def gettag
    @result = Hastag.find_by_photo_id(self.id)
  	if (@result!=nil)
  		return Tag.find_by_id(@result.tag_id).content
  	else
  		return ""
  	end
  end
  def hastag
    @result = Hastag.find_by_photo_id(self.id)
    if (@result!=nil)
      return true
    else
      return false
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_filter :checklogin

    def checklogin
        if session[:user_id] == nil || session[:user_id] == ""
           redirect_to '/error'
          end
    end

  
  # GET /photos
  # GET /photos.json
  def index
    if session[:user_id] != nil 
         redirect_to '/home'
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
    @comments = Comment.where(:photo_id => params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])
    @photo.user_id = session[:user_id]
    @tagcontent = params[:tag]
    if (@tagcontent!="")
      tag = Tag.find_by_content(@tagcontent)
      if (tag !=nil)
        @tag_id = tag.id
      else
        @newtag = Tag.new
        @newtag.content = @tagcontent
        @newtag.save
        @tag_id = @newtag.id
      end
    end

    respond_to do |format|
      if @photo.save
        if (@tagcontent!="")
            @hastag = Hastag.new
            @hastag.photo_id = @photo.id
            @hastag.tag_id = @tag_id
            @hastag.save
        end
        format.html { redirect_to '/home', notice: 'You have uploaded a new photo'}
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])
    @photo_oldtag = @photo.gettag
    @tagcontent = params[:tag]
    if @photo.hastag
          if @tagcontent != @photo_oldtag
              @deletehastag = Hastag.find_by_photo_id(@photo.id)
              @deletehastag.destroy
              if (@tagcontent!="")
                  tag = Tag.find_by_content(@tagcontent)
                  if (tag !=nil)
                    @tag_id = tag.id
                  else
                    @newtag = Tag.new
                    @newtag.content = @tagcontent
                    @newtag.save
                    @tag_id = @newtag.id
                    @hastag = Hastag.new
                    @hastag.photo_id = @photo.id
                    @hastag.tag_id = @tag_id
                    @hastag.save
                  end
              end     
          end
         
    else
        if (@tagcontent!="")
            tag = Tag.find_by_content(@tagcontent)
            if (tag !=nil)
              @tag_id = tag.id
            else
              @newtag = Tag.new
              @newtag.content = @tagcontent
              @newtag.save
              @tag_id = @newtag.id
            end
            @hastag = Hastag.new
            @hastag.photo_id = @photo.id
            @hastag.tag_id = @tag_id
            @hastag.save
        end
    end
    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @hastags = Hastag.where(:photo_id => @photo.id)
    @hastags.destroy_all
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to '/home', notice: 'You have deleted the picture' }
      format.json { head :no_content }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for @photo, :html =>{:multipart => true} do |f| %>
  <% if @photo.errors.any? %>
   
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
   
  <% end %>


  <div class="field">
    <%= f.label :detail %>
    <%= f.text_field :detail %>
  </div>
  <div class="field">
    <input placeholder = "tag" class = "rounded" name="tag" size="30" type="text" />
  </div>
  <div class="field" >

     
          <%= f.file_field :image %>
       </div>
 
  <button class="action green"   >
    <span class="label">
         Upload
    </span>
  </button>

<% end %>

app/views/photos/edit.html.erb
<%= image_tag @photo.image_url.to_s %>
  <%= form_for @photo, :html =>{:multipart => true} do |f| %>
  <% if @photo.errors.any? %>
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  <% end %>

  <div class="field">
    <input id="photo_comment" class ="rounded" placeholder = "detail" name="photo[detail]" size="30" type="text" value="<%=@photo.detail%>" />
  </div>
  <div class="field">
    <input id="photo_tag" name="tag" placeholder = "tag" class ="rounded" size="30" type="text" value="<%=@photo.gettag%>" />
  </div>
  <button class="action green" >
    <span class="label">
    	 Save
    </span>
  </button>

<% end %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.comment %></td>
    <td>
        <%= image_tag photo.image_url(:thumb).to_s %>
    </td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= image_tag "pixome-final.png", :size => '400x200'%>
  Welcome back to piXome

<%= form_for @photo, :html =>{:multipart => true} do |f| %>
  <% if @photo.errors.any? %>
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
  <% end %>


 <div class="field" >
    <input id="photo_comment" placeholder = "detail" name="photo[detail]" size="30" type="text" class="rounded"/>
  </div>
  <div class="field">
    <input id="photo_tag" placeholder = "tag" class = "rounded" name="tag" size="30" type="text"/>
  </div>

<div class="field">

     
          <%= f.file_field :image %>
     
  </div>


  <button class="action green" >
    <span class="label" >
         Upload
    </span>
  </button>

<% end %>

app/views/photos/show.html.erb
	<%= image_tag @photo.image_url(:detail).to_s, :id => "showimage"%>
	<p>
<b>Tag:</b>
  <%= @photo.gettag %>
</p>
	<p>
<b>Detail:</b>
  <%= @photo.detail %>
</p>
	 <% if @photo.user_id == session[:user_id] %>
			<a href="/photos/<%=@photo.id%>/edit" class="button blue">
			Edit
			</a>	
			<a href="/photos/<%=@photo.id%>/destroy" class="button red" class="button blue"  >
			Delete
			</a>	
		
	<% end %>

	<%= form_tag "/comments/new/"+@photo.id.to_s do %>

		  <div class="field">
            <input id="commentcontent" name="commentcontent" class="roundedbig" placeholder="Leave any comments? " size="30" type="text" />
        </div> 

       
        	<a href="https://twitter.com/share" class="twitter-share-button" data-text="I like this picture" data-size="large" data-count="none">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
			</script>
        

		 <% if @photo.user_id == session[:user_id] %>
		        <div id="ImageDetailBoxCommentMakeBoxButtonExtra" >
		 <% else %>
		        <div id="ImageDetailBoxCommentMakeBoxButton" >
		<% end %>
        <button class="action green" >
           	<span class="label">
           		Comment
           	</span>
               
        </button>





		
    <% end %>




	<% @comments.each do |comment|%>
		<% @commentUser = User.find_by_id(comment.user_id) %>
		
				<%= image_tag @commentUser.image_url(:tinythumb).to_s%>
		
			<b><%= @commentUser.username %></b>          said at <%= comment.created_at %>
		
			<%= comment.content %>
		
	<% end %>

<script>
	var image = document.getElementById('showimage');
	offset = (984-image.width)/2
	image.style.cssText = "position:relative;left:"+offset.toString()+"px;visibility:visible";

</script>